[theme]
primaryColor = "#28a745"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#212529"
font = "sans serif"

[client]
showErrorDetails = true

[server]
headless = true
port = 8501
